services:
  db:
    image: postgres:${POSTGRES_VERSION:-18.0-alpine}
    container_name: postgres
    ports:
       - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-folio-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-folio-pass}
      POSTGRES_DB: ${POSTGRES_DB:-folio-app-transactions}

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4.2.0-management-alpine}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-folio-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-folio-pass}

  transactions:
    image: ${TRANSACTIONS_IMAGE:-renansouza-dev/folio-app-transactions}
    container_name: ${TRANSACTIONS_CONTAINER_NAME:-folio-app-transactions}
    build:
      context: ${BUILD_CONTEXT:-..}
      dockerfile: ${DOCKERFILE:-folio-app-web/Dockerfile}
      args:
        SERVICE_NAME: transactions
        JAR_FILE: folio-app-transactions/target/folio-app-transactions-*.jar
    ports:
      - "${TRANSACTIONS_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST:-db}:${DB_PORT:-5432}/${POSTGRES_DB:-folio-app-transactions}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-folio-user}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-folio-pass}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER:-org.postgresql.Driver}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE_TRANSACTIONS:-accounts.queue}
      - RABBITMQ_QUEUE_DLQ=${RABBITMQ_QUEUE_DLQ:-accounts.dead-letter}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE_TRANSACTIONS:-accounts.exchange}
      - RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY:-accounts.#}
    depends_on:
      - db
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'