services:
  db:
    image: postgres:${POSTGRES_VERSION:-18.0-alpine}
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-folio-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-folio-pass}
      POSTGRES_DB: ${POSTGRES_DB:-folio-app-accounts}

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4.2.0-management-alpine}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-folio-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-folio-pass}

  accounts:
    image: ${ACCOUNTS_IMAGE:-renansouza-dev/folio-app-accounts}
    container_name: ${ACCOUNTS_CONTAINER_NAME:-folio-app-accounts}
    build:
      context: ${BUILD_CONTEXT:-..}
      dockerfile: ${DOCKERFILE:-folio-app-web/Dockerfile}
      args:
        SERVICE_NAME: accounts
        JAR_FILE: folio-app-accounts/target/folio-app-accounts-*.jar
    ports:
      - "${ACCOUNTS_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST:-db}:${DB_PORT:-5432}/${POSTGRES_DB:-folio-app-accounts}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-folio-user}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-folio-pass}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER:-org.postgresql.Driver}
    depends_on:
      - db
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'