spring:
  application:
    name: folio-app-transactions
  cache:
    type: caffeine
    cache-names:
      - transactions
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m,recordStats
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/folio-app-transactions}
    username: ${SPRING_DATASOURCE_USERNAME:folio-user}
    password: ${SPRING_DATASOURCE_PASSWORD:folio-pass}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:folio-user}
    password: ${SPRING_RABBITMQ_PASSWORD:folio-pass}

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE:accounts.queue}
    dlq: ${RABBITMQ_QUEUE_DLQ:accounts.dead-letter}
  exchange:
    name: ${RABBITMQ_EXCHANGE:accounts.exchange}
  routing-key: ${RABBITMQ_ROUTING_KEY:accounts.#}

management:
  endpoints:
    web:
      exposure:
        include: health,flyway,metrics,prometheus
  metrics:
    enable:
      cache: true
      caffeine: true
    tags:
      application: ${spring.application.name}