name: Build and Cache

on:
  workflow_call:
    inputs:
      java-distro:
        description: 'Java flavor to use'
        required: true
        default: 'temurin'
        type: string
      java-version:
        description: 'Java version to use'
        required: true
        default: '21'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B compile -DskipTests=true --file pom.xml -ntp
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-