CREATE TABLE transactions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date date NOT NULL,
   type SMALLINT,
   asset VARCHAR(6) NOT NULL,
   price DECIMAL(9) NOT NULL,
   quantity INTEGER NOT NULL,
   fee DECIMAL(9) NOT NULL,
   broker VARCHAR(10) NOT NULL,
   deleted boolean NOT NULL DEFAULT FALSE,
   CONSTRAINT pk_transactions PRIMARY KEY (id)
);