name: Bump project version

on:
  workflow_call:
    inputs:
      java-distro:
        description: 'Java flavor to use'
        default: 'temurin'
        type: string
      java-version:
        description: 'Java version to use'
        default: '21'
        type: string

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            accounts: folio-app-accounts/**
            transactions: folio-app-transactions/**

  update-branches:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    needs: detect-changes
    strategy:
      matrix:
        branch: [develop, release]
        package: ${{ fromJSON(needs.detect-changes.outputs.packages) }}
    steps:
      - name: Checkout repo
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Setup java
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Restore from cache
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Bump version
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Setup java
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Configure Git
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Create a new branch
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Commit changes
        run: echo "::name::${GITHUB_STEP_NAME}"
      - name: Push to remote
        run: echo "::name::${GITHUB_STEP_NAME}"