name: Code Analysis

on:
  workflow_call:
    inputs:
      java-distro:
        description: 'Java flavor to use'
        default: 'temurin'
        type: string
      java-version:
        description: 'Java version to use'
        default: '21'
        type: string

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distro }}
          cache: maven
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List Environment Variables
        run: printenv
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}