name: Bump project version

on:
  workflow_call:
    inputs:
      java-distro:
        description: 'Java flavor to use'
        default: 'temurin'
        type: string
      java-version:
        description: 'Java version to use'
        default: '21'
        type: string

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

      - name: Fetch release branch
        run: |
          git fetch origin release || echo "Branch release not found"
          git checkout release || git checkout -b release origin/release

      - name: Merge develop into release
        run: |
          git merge develop --allow-unrelated-histories || echo "No changes to merge"

      - name: Remove snapshot from pom.xml
        run: |
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git status
          git add .
          git commit -m "Remove -SNAPSHOT from pom.xml" || echo "No changes to commit"

      - name: Push changes to release branch
        run: |
          git push origin release